SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE MEMBER;
TRUNCATE TABLE REFRESH_TOKEN;
TRUNCATE TABLE COMMENT;
TRUNCATE TABLE COMMENT_LIKE;
TRUNCATE TABLE MEME;
TRUNCATE TABLE TITLE;
TRUNCATE TABLE TITLE_LIKE;
TRUNCATE TABLE TOP_TITLE;


SET REFERENTIAL_INTEGRITY TRUE;